#!/bin/bash
# generate-keys.sh — Generate cryptographic secrets for ASE
# Run once before first deployment: bash scripts/generate-keys.sh
set -e

cd "$(dirname "$0")/.."

echo "Generating ASE secrets..."

# Check Python dependencies
if ! python3 -c "from cryptography.fernet import Fernet" 2>/dev/null; then
    echo "Installing required Python packages..."
    pip3 install cryptography bcrypt --quiet
fi

# Generate FERNET_KEY (base64-encoded 32-byte key for Shopify token encryption)
FERNET_KEY=$(python3 -c "from cryptography.fernet import Fernet; print(Fernet.generate_key().decode())")

# Generate SECRET_KEY (32 random bytes base64 for CSRF / misc signing)
SECRET_KEY=$(python3 -c "import secrets, base64; print(base64.urlsafe_b64encode(secrets.token_bytes(32)).decode())")

# Prompt for admin password and hash it with bcrypt
echo ""
read -s -p "Set admin password: " ADMIN_PASSWORD
echo ""
read -s -p "Confirm admin password: " ADMIN_PASSWORD2
echo ""

if [ "$ADMIN_PASSWORD" != "$ADMIN_PASSWORD2" ]; then
    echo "ERROR: Passwords don't match"
    exit 1
fi

if [ ${#ADMIN_PASSWORD} -lt 8 ]; then
    echo "ERROR: Password must be at least 8 characters"
    exit 1
fi

ADMIN_PASSWORD_HASH=$(python3 -c "
import bcrypt
pwd = b'$ADMIN_PASSWORD'
print(bcrypt.hashpw(pwd, bcrypt.gensalt(rounds=12)).decode())
")

# Write to .env.local (git-ignored)
cat > .env.local <<EOF
# Generated by scripts/generate-keys.sh
# DO NOT COMMIT THIS FILE — it is listed in .gitignore
FERNET_KEY=$FERNET_KEY
SECRET_KEY=$SECRET_KEY
ADMIN_PASSWORD_HASH=$ADMIN_PASSWORD_HASH
POSTGRES_PASSWORD=ase_dev_password
MINIO_ACCESS_KEY=minioadmin
MINIO_SECRET_KEY=minioadmin
GRAFANA_PASSWORD=admin
ENVIRONMENT=development
LOG_LEVEL=INFO
EOF

echo "Keys generated and saved to .env.local"
echo ""
echo "Next steps:"
echo "  1. Copy API keys to .env (DEEPSEEK_API_KEY, etc.)"
echo "  2. Run: bash scripts/setup.sh"
